// Reposition existing PNG layers only. No pictorial assets are drawn by this script.
const fs=require('fs'),path=require('path'),sharp=require('C:/Users/sinna/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/sharp');
const R=path.resolve(__dirname,'..'),screens=require('../layouts/screens.json'),cache=new Map(),changes=[],checks=[];
async function bounds(file){if(cache.has(file))return cache.get(file);const {data,info}=await sharp(path.join(R,file)).ensureAlpha().raw().toBuffer({resolveWithObject:true});let l=info.width,t=info.height,r=-1,b=-1;for(let y=0;y<info.height;y++)for(let x=0;x<info.width;x++)if(data[(y*info.width+x)*4+3]>64){l=Math.min(l,x);t=Math.min(t,y);r=Math.max(r,x);b=Math.max(b,y)}const v={left:l,top:t,width:r-l+1,height:b-t+1,data,info};cache.set(file,v);return v}
async function face(file){const a=await bounds(file),{data,info}=a;const good=[];for(let y=0;y<info.height;y++){let bright=0,n=0;for(let x=Math.floor(info.width*.38);x<info.width*.62;x++){let p=(y*info.width+x)*4;if(data[p+3]<160)continue;n++;const lum=.2126*data[p]+.7152*data[p+1]+.0722*data[p+2];if(lum>143)bright++}good.push(n>0&&bright/n>.7)}let runs=[];for(let y=0;y<good.length;y++){if(good[y]){let start=y;while(y+1<good.length&&good[y+1])y++;runs.push({start,end:y,len:y-start+1})}}const run=runs.sort((a,b)=>b.len-a.len)[0];if(!run)throw new Error('Cannot locate painted button face: '+file);return{x:info.width/2,y:(run.start+run.end)/2,top:run.start,bottom:run.end,method:'bright painted face, central 24% columns; excludes dark wooden base'};}
function move(s,e,x,y,reason){x=Math.round(x);y=Math.round(y);if(x!==e.x||y!==e.y)changes.push({screen:s.id,id:e.id,text:e.textContent,reason,before:{x:e.x,y:e.y},after:{x,y},delta:{x:x-e.x,y:y-e.y}});e.x=x;e.y=y;e.yScene2D=1920-y-e.height;}
async function position(s,e,cx,cy,reason){const b=await bounds(e.asset);move(s,e,cx-b.left-b.width/2,cy-b.top-b.height/2,reason);return b}
async function align(){for(const s of screens){for(const e of s.elements){if(e.buttonOwner&&!s.elements.some(b=>b.id===e.buttonOwner)&&s.elements.some(b=>b.id==="ranking-content-"+e.buttonOwner))e.buttonOwner="ranking-content-"+e.buttonOwner}const handled=new Set();for(const btn of s.elements.filter(e=>e.states)){const f=await face(btn.asset);const cx=btn.x+f.x,cy=btn.y+f.y;btn.contentFace={x:btn.x+8,y:btn.y+f.top,width:btn.width-16,height:f.bottom-f.top+1,center:{x:cx,y:cy},method:f.method};const texts=s.elements.filter(e=>e.buttonOwner===btn.id);const icons=s.elements.filter(e=>e.sourceAsset?.includes('/icons/')&&e.x>=btn.x&&e.y>=btn.y&&e.x+e.width<=btn.x+btn.width&&e.y+e.height<=btn.y+btn.height&&!e.characterId);const extra=s.elements.filter(e=>e.textContent==='에너지 1'&&btn.action?.target===null&&e.x>=btn.x&&e.x+e.width<=btn.x+btn.width&&e.y>=btn.y&&e.y<btn.y+btn.height);texts.push(...extra);const members=[...icons,...texts];if(!members.length)continue;
if(texts.length<=1){const widths=await Promise.all(members.map(async e=>(await bounds(e.asset)).width));const gap=members.length>1?Math.min(18,btn.width*.055):0;const total=widths.reduce((a,b)=>a+b,0)+gap*(members.length-1);let left=cx-total/2;for(let i=0;i<members.length;i++){const e=members[i];await position(s,e,left+widths[i]/2,cy,'button visible content centered on painted face');left+=widths[i]+gap;handled.add(e.id)}}else{const bs=await Promise.all(texts.map(e=>bounds(e.asset)));const gap=8,total=bs.reduce((n,b)=>n+b.height,0)+gap*(bs.length-1);const tw=Math.max(...bs.map(b=>b.width)),ib=icons.length?await bounds(icons[0].asset):null,iw=ib?.width||0,groupWidth=tw+iw+(iw?18:0),groupLeft=cx-groupWidth/2,textCx=groupLeft+iw+(iw?18:0)+tw/2;let top=cy-total/2;for(let i=0;i<texts.length;i++){await position(s,texts[i],textCx,top+bs[i].height/2,'stacked production label centered on painted face');top+=bs[i].height+gap;handled.add(texts[i].id)}for(const ico of icons){await position(s,ico,groupLeft+iw/2,cy,'production icon centered on painted face');handled.add(ico.id)}}
btn.alignmentStateOffsets={};for(const[state,file]of Object.entries(btn.states)){const ff=await face(file);btn.alignmentStateOffsets[state]={x:0,y:Math.round(ff.y-f.y)}}
for(const e of members){const b=await bounds(e.asset);const ay=e.y+b.top+b.height/2;checks.push({screen:s.id,owner:btn.id,element:e.id,kind:'button',text:e.textContent,faceCenter:cy,visibleCenter:ay,verticalError:texts.length>1?null:Math.abs(ay-cy)});e.alignmentOwner=btn.id;}
}
// Center single-line title strips and meter labels; body copy deliberately retains its left/right alignment.
for(const e of s.elements.filter(e=>e.semanticType==='text'&&e.align==='center'&&!handled.has(e.id))){const containers=s.elements.filter(p=>p.type==='image'&&p.id!==e.id&&p.z<e.z&&(p.sourceAsset?.includes('title-banner')||p.sourceAsset?.includes('progress-track')||p.sourceAsset?.includes('panel-'))&&p.x<=e.x+2&&p.x+p.width>=e.x+e.width-2&&p.y<=e.y&&p.y+p.height>=e.y+e.height&&p.height<=160).sort((a,b)=>a.width*a.height-b.width*b.height);const p=containers[0];if(p){await position(s,e,p.x+p.width/2,p.y+p.height/2,'centered strip/title/meter label uses visible glyph bounds');handled.add(e.id)}else{const b=await bounds(e.asset);e.alignmentAxisX??=e.x+e.width/2;move(s,e,e.alignmentAxisX-b.left-b.width/2,e.y,'horizontal center uses visible glyph bounds')}}
// Five bottom-navigation groups: center each painted icon and visible text on the tab axis.
const nav=s.elements.filter(e=>e.type==='hit'&&e.y>=1730&&e.height<=165&&e.width>=180&&e.width<=205);for(const tab of nav){const cx=tab.x+tab.width/2;for(const e of s.elements.filter(e=>e.type==='image'&&e.x>=tab.x-2&&e.x+e.width<=tab.x+tab.width+2&&e.y>=tab.y&&e.y<tab.y+tab.height&&(e.semanticType==='text'||e.sourceAsset?.includes('/icons/')))){const b=await bounds(e.asset);move(s,e,cx-b.left-b.width/2,e.y,'navigation visible content centered on tab axis')}}
// Keep every text layer inside the viewport after removing its font-side whitespace offset.
for(const e of s.elements){if(e.type==='image'){move(s,e,Math.max(0,Math.min(1080-e.width,e.x)),Math.max(0,Math.min(1920-e.height,e.y)), 'canvas containment');}}
const comp=[];for(const e of s.elements.filter(e=>e.type==='image'))comp.push({input:path.join(R,e.asset),left:e.x,top:e.y});await sharp({create:{width:1080,height:1920,channels:4,background:'#00000000'}}).composite(comp).png().toFile(path.join(R,'screens',s.id+'.png'));fs.writeFileSync(path.join(R,'layouts',s.id+'.json'),JSON.stringify(s,null,2));}
fs.writeFileSync(path.join(R,'layouts/screens.json'),JSON.stringify(screens,null,2));fs.writeFileSync(path.join(R,'screens-data.js'),'window.SCREENS='+JSON.stringify(screens)+';');const groupChecks=[];for(const s of screens)for(const btn of s.elements.filter(e=>e.contentFace)){const members=s.elements.filter(e=>e.alignmentOwner===btn.id);if(!members.length)continue;let left=Infinity,right=-Infinity,top=Infinity,bottom=-Infinity;for(const e of members){const b=await bounds(e.asset);left=Math.min(left,e.x+b.left);right=Math.max(right,e.x+b.left+b.width);top=Math.min(top,e.y+b.top);bottom=Math.max(bottom,e.y+b.top+b.height)}const c=btn.contentFace.center;groupChecks.push({screen:s.id,button:btn.id,horizontalError:Math.abs((left+right)/2-c.x),verticalError:Math.abs((top+bottom)/2-c.y)})}const failed=groupChecks.filter(c=>c.horizontalError>1||c.verticalError>1);fs.writeFileSync(path.join(R,'docs/alignment-audit.json'),JSON.stringify({status:failed.length?'FAIL':'PASS',screens:screens.length,buttons:screens.reduce((n,s)=>n+s.elements.filter(e=>e.states).length,0),changedElements:new Set(changes.map(c=>c.screen+':'+c.id)).size,checks,groupChecks,changes,failed},null,2));
const samples=[];for(const id of['modes','workshop','cats','shop','ranking','settings','purchase','battle']){const s=screens.find(s=>s.id===id);for(const btn of s.elements.filter(e=>e.states&&s.elements.some(t=>t.buttonOwner===e.id)).slice(0,6)){const x=Math.max(0,btn.x-8),y=Math.max(0,btn.y-8),w=Math.min(1080-x,btn.width+16),h=Math.min(1920-y,btn.height+16);samples.push(await sharp(path.join(R,'screens',s.id+'.png')).extract({left:x,top:y,width:w,height:h}).resize(400,110,{fit:'contain',background:'#ede9df'}).png().toBuffer())}}
await sharp({create:{width:1200,height:Math.ceil(samples.length/3)*126,channels:4,background:'#ede9df'}}).composite(samples.map((input,i)=>({input,left:i%3*400,top:Math.floor(i/3)*126}))).png().toFile(path.join(R,'previews/aligned-buttons.png'));console.log(JSON.stringify({screens:screens.length,changes:changes.length,checkedButtonElements:checks.length,failed:failed.length}));if(failed.length)process.exitCode=1;}
align().catch(e=>{console.error(e);process.exitCode=1});
