const fs=require('fs'),path=require('path'),crypto=require('crypto');
const sharp=require('C:/Users/sinna/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/sharp');
const R=path.resolve(__dirname,'..');const spec=require('../production.json');
const mkdir=p=>fs.mkdirSync(p,{recursive:true});const write=(p,v)=>{mkdir(path.dirname(p));fs.writeFileSync(p,typeof v==='string'?v:JSON.stringify(v,null,2))};
async function inspectAlpha(buf){const {data,info}=await sharp(buf).ensureAlpha().raw().toBuffer({resolveWithObject:true});let empty=0,minX=info.width,minY=info.height,maxX=-1,maxY=-1;for(let y=0;y<info.height;y++)for(let x=0;x<info.width;x++){const a=data[(y*info.width+x)*4+3];if(a<8)empty++;if(a>8){minX=Math.min(minX,x);maxX=Math.max(maxX,x);minY=Math.min(minY,y);maxY=Math.max(maxY,y)}}return{fraction:empty/(info.width*info.height),bounds:{left:minX,top:minY,width:maxX-minX+1,height:maxY-minY+1},width:info.width,height:info.height};}
async function main(){const manifest=[],missing=[];for(const job of spec.jobs){const source=path.join(R,'sources',job.id+'.png');if(!fs.existsSync(source)){missing.push(job.id);continue}const meta=await sharp(source).metadata();if(job.kind==='background'){const dest='assets/backgrounds/'+job.id.slice(3)+'.png';mkdir(path.dirname(path.join(R,dest)));await sharp(source).resize(1080,1920,{fit:'cover'}).png().toFile(path.join(R,dest));manifest.push({id:job.id,file:dest,source:'sources/'+job.id+'.png',width:1080,height:1920,alpha:false});continue}
const cells=job.names||[job.id];const cols=job.cols||1,rows=job.rows||1;
const raw=await sharp(source).ensureAlpha().raw().toBuffer();
// Generated atlases have unequal outer padding. Find actual transparent gutters instead of assuming exact uniform crop boundaries.
function separators(length,count,profile){if(count===1)return[0,length];const threshold=Math.max(1,Math.max(...profile)*.003);let first=profile.findIndex(v=>v>threshold),last=length-1;while(last>first&&profile[last]<=threshold)last--;const gaps=[];for(let p=first;p<last;p++){if(profile[p]<=threshold){let start=p;while(p<last&&profile[p]<=threshold)p++;if(p-start>=3)gaps.push({mid:Math.round((p+start)/2),size:p-start})}}if(gaps.length>=count-1)return[0,...gaps.sort((a,b)=>b.size-a.size).slice(0,count-1).map(g=>g.mid).sort((a,b)=>a-b),length];const cuts=[0];for(let i=1;i<count;i++){let best=Math.round(i*length/count),score=Infinity;const mid=i*length/count,radius=length/count*.4;for(let p=Math.ceil(mid-radius);p<=Math.floor(mid+radius);p++){let occupancy=0;for(let k=-2;k<=2;k++)occupancy+=(profile[p+k]||0);const candidate=occupancy*10000+Math.abs(p-mid);if(candidate<score){score=candidate;best=p}}cuts.push(best)}cuts.push(length);return cuts}
const yp=new Array(meta.height).fill(0);for(let y=0;y<meta.height;y++)for(let x=0;x<meta.width;x++)if(raw[(y*meta.width+x)*4+3]>24)yp[y]++;const ys=separators(meta.height,rows,yp),xrows=[];for(let r=0;r<rows;r++){const xp=new Array(meta.width).fill(0);for(let y=ys[r];y<ys[r+1];y++)for(let x=0;x<meta.width;x++)if(raw[(y*meta.width+x)*4+3]>24)xp[x]++;xrows.push(separators(meta.width,cols,xp))}
for(let i=0;i<cells.length;i++){const r=Math.floor(i/cols),c=i%cols,x0=xrows[r][c],y0=ys[r],x1=xrows[r][c+1],y1=ys[r+1];let buf=await sharp(source).extract({left:x0,top:y0,width:x1-x0,height:y1-y0}).ensureAlpha().png().toBuffer();let a=await inspectAlpha(buf);if(a.fraction<.02)throw new Error('No genuine alpha: '+job.id+' cell '+i+'; regenerate transparent source');const b=a.bounds;if(b.width<8||b.height<8)throw new Error('Empty cell '+cells[i]);const cut=await sharp(buf).extract(b).png().toBuffer();const folder=job.kind==='character'?'characters':job.id.startsWith('items-')?'items':job.id.startsWith('icons-')?'icons':'ui';const dest='assets/'+folder+'/'+cells[i]+'.png';mkdir(path.dirname(path.join(R,dest)));await sharp(cut).extend({top:4,bottom:4,left:4,right:4,background:'#00000000'}).png().toFile(path.join(R,dest));manifest.push({id:cells[i],file:dest,source:'sources/'+job.id+'.png',sourceCell:{x:x0,y:y0,width:x1-x0,height:y1-y0},sourceTrim:b,width:b.width+8,height:b.height+8,alpha:true,transparentFraction:a.fraction,sha256:crypto.createHash('sha256').update(fs.readFileSync(path.join(R,dest))).digest('hex')});}}
const unique=[...new Map(manifest.map(a=>[a.id,a])).values()];write(path.join(R,'assets','manifest.json'),unique);write(path.join(R,'docs','extraction-status.json'),{assets:unique.length,missing,complete:missing.length===0});console.log(JSON.stringify({assets:unique.length,missing}));}
main().catch(e=>{console.error(e);process.exitCode=1});
