const fs=require('fs'),path=require('path'),crypto=require('crypto');
const sharp=require('C:/Users/sinna/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/sharp');
const ROOT=path.resolve(__dirname,'..','build');const screens=JSON.parse(fs.readFileSync(path.join(ROOT,'layouts','screens.json'))),ids=new Set(screens.map(s=>s.id));const issues=[],warnings=[],used=new Set();
const check=(v,m)=>{if(!v)issues.push(m)};const hash=b=>crypto.createHash('sha256').update(b).digest('hex');
async function main(){
 for(const s of screens){const es=new Set();for(const e of s.elements){check(!es.has(e.id),s.id+': duplicate '+e.id);es.add(e.id);check(e.width>0&&e.height>0&&e.x>=0&&e.y>=0&&e.x+e.width<=1080.1&&e.y+e.height<=1920.1,s.id+': out of bounds '+e.id);if(e.asset){used.add(e.asset);check(fs.existsSync(path.join(ROOT,e.asset)),s.id+': missing '+e.asset)}if(e.action?.target)check(ids.has(e.action.target),s.id+': missing target '+e.action.target);if(e.states)for(const p of Object.values(e.states))check(fs.existsSync(path.join(ROOT,p)),s.id+': missing button state '+p);if(e.hitRect){const r=e.hitRect;check(r.x>=0&&r.y>=0&&r.x+r.width<=1080.1&&r.y+r.height<=1920.1,s.id+': hit area outside screen '+e.id)}}const m=await sharp(path.join(ROOT,'screens',s.id+'.png')).metadata();check(m.width===1080&&m.height===1920,s.id+': wrong screen dimensions')}
 const rigs=JSON.parse(fs.readFileSync(path.join(ROOT,'characters','manifest.json')));let frames=0;const invariants=[];
 for(const rig of rigs){const dir=path.join(ROOT,'characters',rig.id),body=fs.readFileSync(path.join(dir,'body.png')),bodyHash=hash(body);check(bodyHash===rig.body.sha256,rig.id+': body source hash');
  for(const frame of rig.frames){frames++;check(frame.body.sha256===bodyHash&&frame.body.scaleX===1&&frame.body.scaleY===1&&frame.body.rotation===0,rig.id+': body invariant failed');const {data,info}=await sharp(path.join(dir,frame.file)).ensureAlpha().raw().toBuffer({resolveWithObject:true});check(info.width===512&&info.height===512,rig.id+': frame dimensions');let border=0,transparent=0;for(let y=0;y<512;y++)for(let x=0;x<512;x++){const a=data[(y*512+x)*4+3];if(a===0)transparent++;if((x===0||y===0||x===511||y===511)&&a>16)border++}check(border===0,rig.id+': clipped frame '+frame.file);check(transparent>512*512*.15,rig.id+': alpha missing');
  // Compare upper face region against translated immutable body, outside all tool/effect regions.
  const source=await sharp(body).ensureAlpha().raw().toBuffer();let compared=0,mismatches=0;for(let y=70;y<230;y++)for(let x=165;x<310;x++){const di=((y+frame.body.y)*512+x+frame.body.x)*4,si=(y*512+x)*4;if(source[si+3]===255){compared++;for(let c=0;c<4;c++)if(Math.abs(source[si+c]-data[di+c])>1){mismatches++;break}}}check(mismatches===0,rig.id+': face pixel drift '+frame.file+' '+mismatches);invariants.push({character:rig.id,frame:frame.file,facePixelsCompared:compared,faceMismatches:mismatches,bodySha256:bodyHash});
  }
 }
 const report={status:issues.length?'FAIL':'PASS',screens:screens.length,elements:screens.reduce((n,s)=>n+s.elements.length,0),uniquePlacedAssets:used.size,characters:rigs.length,frames,checks:['asset references','navigation targets','canvas dimensions','element bounds','button state files','hit area bounds','transparent frame borders','fixed body source hash and scale','actual rendered face pixel identity'],issues,warnings,invariants};fs.writeFileSync(path.join(ROOT,'docs','validation.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({...report,invariants:undefined},null,2));if(issues.length)process.exitCode=1;
}
main().catch(e=>{console.error(e);process.exit(1)});
