const fs=require('fs'),path=require('path');
const {chromium}=require('C:/Users/sinna/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const ROOT=path.resolve(__dirname,'..','build');
async function main(){const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',args:['--disable-gpu','--no-first-run','--disk-cache-dir=D:/CodexData/temp/edge-cache']});const page=await browser.newPage({viewport:{width:1480,height:1100},deviceScaleFactor:1});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('file:///'+path.join(ROOT,'index.html').replaceAll('\\','/'));await page.evaluate(()=>document.fonts.ready);await page.waitForFunction(()=>[...document.images].filter(i=>i.closest('#stage')).every(i=>i.complete&&i.naturalWidth>0));
const fontLoaded=await page.evaluate(()=>document.fonts.check('32px "Noto Sans KR"'));
await page.screenshot({path:path.join(ROOT,'previews','inspector.png'),fullPage:true});
const widthProblems=await page.evaluate(()=>{const canvas=document.createElement('canvas'),ctx=canvas.getContext('2d'),bad=[];for(const s of SCREENS)for(const e of s.elements.filter(e=>e.type==='text')){ctx.font=`${e.fontWeight} ${e.fontSize}px "Noto Sans KR"`;const measured=ctx.measureText(e.text).width;if(measured>e.width+1)bad.push({screen:s.id,id:e.id,text:e.text,width:e.width,measured})}return bad});
await page.locator('#navigate').click();await page.locator('#stage [data-id^="nav-hit"]').nth(1).click();const navTitle=await page.locator('#title').innerText();
await page.locator('#view-gallery').click();const thumbs=await page.locator('.thumb').count();await page.locator('#view-anim').click();const animCount=await page.locator('[data-animated]').count();await page.waitForTimeout(250);const frameA=await page.locator('[data-animated]').first().getAttribute('src');await page.waitForFunction(a=>document.querySelector('[data-animated]').getAttribute('src')!==a,frameA);const frameB=await page.locator('[data-animated]').first().getAttribute('src');await page.screenshot({path:path.join(ROOT,'previews','animations.png'),fullPage:true});
const report={status:errors.length||widthProblems.length||!fontLoaded||navTitle!=='우리 고양이들'||animCount!==6||frameA===frameB?'FAIL':'PASS',fontLoaded,navigationTitle:navTitle,galleryScreens:thumbs,animationCharacters:animCount,animationFrameA:frameA,animationFrameB:frameB,errors,textOverflows:widthProblems};fs.writeFileSync(path.join(ROOT,'docs','browser-validation.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));await browser.close();if(report.status==='FAIL')process.exitCode=1}
main().catch(e=>{console.error(e);process.exit(1)});
